### ISSUE TITLE
Push setLanguage at the beginning of the beforeAction handler list

### ISSUE THREAD

**Issue by Raven0us** [cetver/yii2-languages-dispatcher#3]
I'm talking about `Component` and the handler that's attached for `EVENT_BEFORE_ACTION`, the event that actually sets the language.

In a real life scenario, the language should always be handled first, before doing other things. A lot of modules including security ones (RBAC/Access Control) get attached on `EVENT_BEFORE_ACTION` as well. In my case, I need to know the language before doing dynamic stuff and I get the language too late.

Can we go
`$app->on($app::EVENT_BEFORE_ACTION, [$this, 'setLanguage'], $app, false);`? Am I missing something (why we wouldn't want that)?

**Comment by cetver** [comment]
https://github.com/cetver/yii2-languages-dispatcher/releases/tag/1.1.1
