### ISSUE TITLE
setLanguage and AcceptLanguageHeaderHandler issue

### ISSUE THREAD

**Issue by krissce** [cetver/yii2-languages-dispatcher#5]
Hi,
I had an issue with setting yii2 application language based on browser language. After debugging I found out that this line https://github.com/cetver/yii2-languages-dispatcher/blob/466d898f04ceb184526b57fd7f674ab4dc7161d3/Component.php#L92 has an issue. If browser returns more languages that are accepted like I got, for instance pl,en,de then if you got languagesDispatcher languages set to ['en', 'pl', 'de'] in web.php config file then first language was set as default from this array which is 'en' , but it should set first language that is sent by the browser which is here 'pl'. 

Anyway, when I have changed this line to this (switched params): 
$intersection = array_intersect($handler->getLanguages(), $this->languages); 
then browser langauge detection works fine. 

Hope my explanation is clear enough for you to fix this in your code.

Thanks

**Comment by cetver** [comment]
> but it should set first language that is sent by the browser which is here 'pl'.

Why not "de" ?

I want to say that in the "Accept-Language" header, user sets (downloads a browser in its language) his native language first then all the other languages he knows.
Your "Accept-Language" header looks like "en,pl,de" and the component thinks that your native language is "en"
Everything works as expected

**Comment by krissce** [comment]
My 'Accept-Language' was 'pl,en,de' (browser in Polish by default) yet site was displayed in English by default until I have changed this code I've mentioned.

**Comment by cetver** [comment]
Fixed, thanks.
https://github.com/cetver/yii2-languages-dispatcher/releases/tag/1.1.2
